sequenceDiagram
    participant Client
    participant Server

    Client->>Server: Initial Request
    Server->>Client: HTML

    Client->>Server: API Request [AJAX]
    Server->>Client: JSON [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]